GET: http://${host}:${port}/check

//Get all movies with pagination and search options
//search & page are optional
GET: http://${host}:${port}/movies?search=${searchtext}&&page=${pageNumber}

//Admin Auth
POST: http://${host}:${port}/admin/signup
{
    "username": "michael scott",
    "email": "mscott@fyndmovie.com",
    "password": "jan786"
}

POST: http://${host}:${port}/admin/signin -> token in response
{
    "email": "mscott@fyndmovie.com",
    "password": "jan786"
}

//Admin specific routes, needs access_token
POST: http://${host}:${port}/admin/movie
{
    Authorization:${token}
}
{
    "99popularity": 100,
    "name": "de dhakka",
    "imdb_score": 9.0,
    "director": "mahesh manjarekar",
    "genre": ["comedy", "drama"]
}

PUT: http://${host}:${port}/admin/movie/:movieId
{
    Authorization:${token}
}
{
    "99popularity": 99
}

DELETE: http://${host}:${port}/admin/movie/:movieId
{
    Authorization:${token}
}

//for getting list of all genres
GET: http://${host}:${port}/admin/genres
{
    Authorization:${token}
}